src/Entity/Patient.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PatientRepository")
 */
class Patient
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=16)
     */
    private $numero_avs;

    /**
     * @ORM\Column(type="date")
     */
    private $date_naissance;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Admission", mappedBy="patient")
     */
    private $admissions;
// ---------------------------------------------------------------------------------------------------

    public function __construct()
    {
        $this->admissions = new ArrayCollection();
    }
// ---------------------------------------------------------------------------------------------------

    public function __toString()
    {
        return $this->getNom(). " ".$this->getPrenom();
    }
// ---------------------------------------------------------------------------------------------------

    public function getId(): ?int
    {
        return $this->id;
    }
// ---------------------------------------------------------------------------------------------------

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }
// ---------------------------------------------------------------------------------------------------

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }
// ---------------------------------------------------------------------------------------------------

    public function getNumeroAvs(): ?string
    {
        return $this->numero_avs;
    }

    public function setNumeroAvs(string $numero_avs): self
    {
        $this->numero_avs = $numero_avs;

        return $this;
    }
// ---------------------------------------------------------------------------------------------------

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }
// ---------------------------------------------------------------------------------------------------

    /**
     * @return Collection|Admission[]
     */
    public function getAdmissions(): Collection
    {
        return $this->admissions;
    }

    public function addAdmission(Admission $admission): self
    {
        if (!$this->admissions->contains($admission)) {
            $this->admissions[] = $admission;
            $admission->setPatient($this);
        }

        return $this;
    }

    public function removeAdmission(Admission $admission): self
    {
        if ($this->admissions->contains($admission)) {
            $this->admissions->removeElement($admission);
            // set the owning side to null (unless already changed)
            if ($admission->getPatient() === $this) {
                $admission->setPatient(null);
            }
        }

        return $this;
    }
// ---------------------------------------------------------------------------------------------------

}

src/Form/PatientType.php
<?php

namespace App\Form;

use App\Entity\Patient;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PatientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('numero_avs')
            ->add('date_naissance')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Patient::class,
        ]);
    }
}

src/Controller/PatientController.php
<?php

namespace App\Controller;

use App\Entity\Admission;
use App\Entity\Patient;
use App\Form\PatientType;
use App\Form\AdmissionType;
use App\Repository\PatientRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/patient")
 */
class PatientController extends AbstractController
{
    /**
     * @Route("/", name="patient_index", methods={"GET","POST"})
     */
    public function index(PatientRepository $patientRepository, Request $request): Response
    {
        $patient = new Patient();
        $form = $this->createForm(PatientType::class, $patient);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($patient);
            $entityManager->flush();

            return $this->redirectToRoute('patient_index');
        }

        return $this->render('patient/index.html.twig', [
            'patients' => $patientRepository->findAll(),
            'form' => $form->createView(),
        ]);
    }

    // fuck la methode new !!

    /**
     * @Route("/{id}", name="patient_show", methods={"GET","POST"})
     */
    public function show(Patient $patient, Request $request): Response
    {

        $formEditPatient = $this->createForm(PatientType::class, $patient);
        $formEditPatient->handleRequest($request);

        if ($formEditPatient->isSubmitted() && $formEditPatient->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('patient_index');
        }
// ------------------------------------------------------------------------------

        $admission = new Admission();

        $admission->setPatient($patient);      // je set le patient en cours

        $form = $this->createForm(AdmissionType::class, $admission);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($admission);
            $entityManager->flush();

            return $this->redirectToRoute('admission_index');
        }

        return $this->render('patient/show.html.twig', [
            'patient' => $patient,
            'admission' => $admission,
            'form' => $form->createView(),
            'patientForm' => $formEditPatient->createView(),

        ]);
    }

    /**
     * @Route("/{id}/edit", name="patient_edit", methods={"GET","POST"})
     */
    // public function edit(Request $request, Patient $patient): Response
    // {
    //     $form = $this->createForm(PatientType::class, $patient);
    //     $form->handleRequest($request);

    //     if ($form->isSubmitted() && $form->isValid()) {
    //         $this->getDoctrine()->getManager()->flush();

    //         return $this->redirectToRoute('patient_index');
    //     }

    //     return $this->render('patient/edit.html.twig', [
    //         'patient' => $patient,
    //         'form' => $form->createView(),
    //     ]);
    // }

    /**
     * @Route("/{id}", name="patient_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Patient $patient): Response
    {
        if ($this->isCsrfTokenValid('delete'.$patient->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($patient);
            $entityManager->flush();
        }

        return $this->redirectToRoute('patient_index');
    }
}

templates/patient/_delete_form.html.twig
<form method="post" action="{{ path('patient_delete', {'id': patient.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ patient.id) }}">
    <button class="btn">Delete</button>
</form>

templates/patient/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/patient/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Patient index{% endblock %}


{% block body %}
    <h1>Patient index</h1>

    <table class="table">
        <thead>
            <tr>
                {# <th>Id</th> #}
                <th>Nom</th>
                <th>Prenom</th>
                {# <th>Numero_avs</th>
                <th>Date_naissance</th> #}
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for patient in patients %}
            <tr>
                {# <td>{{ patient.id }}</td> #}
                <td>{{ patient.nom }}</td>
                <td>{{ patient.prenom }}</td>
                {# <td>{{ patient.numeroAvs }}</td>
                <td>{{ patient.dateNaissance ? patient.dateNaissance|date('Y-m-d') : '' }}</td> #}
                <td>
                    <a href="{{ path('patient_show', {'id': patient.id}) }}">show</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">rien trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <h2>Ajouter patient</h2>

    {{ include('patient/_form.html.twig') }}



{% endblock %}

templates/patient/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Patient{% endblock %}

{% block body %}
    <h1>Patient</h1>
{#                                        ?? et bien avant le label qui est sencé changer le "save" de base mais ca marche pas                #}
    {{ include('patient/_form.html.twig',{form:patientForm}, {'button_label': 'Update'} ) }}

    <a href="{{ path('patient_index') }}">retour à la liste</a>

    {# <a href="{{ path('patient_edit', {'id': patient.id}) }}">edit</a> noneed#}

    {{ include('patient/_delete_form.html.twig') }}

        <h2>Interner</h2>

    {{ include('admission/_form.html.twig') }}

{% endblock %}