src/Entity/Admission.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AdmissionRepository")
 */
class Admission
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_debut;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_fin;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Patient", inversedBy="admissions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $patient;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Chambre", inversedBy="admissions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $chambre;
// ---------------------------------------------------------------------------------------------------

    public function getId(): ?int
    {
        return $this->id;
    }
// ---------------------------------------------------------------------------------------------------

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;
        
        return $this;
    }
// ---------------------------------------------------------------------------------------------------
    public function __construct()
    {
        $this->setDateDebut = (new \DateTime('now'));
    }

// ---------------------------------------------------------------------------------------------------

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;
        
        return $this;
    }
// ---------------------------------------------------------------------------------------------------

    public function getPatient(): ?patient
    {
        return $this->patient;
    }

    public function setPatient(?patient $patient): self
    {
        $this->patient = $patient;
        
        return $this;
    }
// ---------------------------------------------------------------------------------------------------

    public function getChambre(): ?chambre
    {
        return $this->chambre;
    }

    public function setChambre(?chambre $chambre): self
    {
        $this->chambre = $chambre;
        
        return $this;
    }
// ---------------------------------------------------------------------------------------------------

}

src/Entity/Hopital.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\HopitalRepository")
 */
class Hopital
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $code_postale;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=2)
     */
    private $pays;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Chambre", mappedBy="hopital")
     */
    private $chambres;
// ---------------------------------------------------------------------------------------------------

    public function __construct()
    {
        $this->chambres = new ArrayCollection();
    }
// ---------------------------------------------------------------------------------------------------

    public function __toString()
    {
        return $this->getNom();
    }
// ---------------------------------------------------------------------------------------------------

    public function getId(): ?int
    {
        return $this->id;
    }
// ---------------------------------------------------------------------------------------------------

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }
// ---------------------------------------------------------------------------------------------------

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }
// ---------------------------------------------------------------------------------------------------

    public function getCodePostale(): ?string
    {
        return $this->code_postale;
    }

    public function setCodePostale(string $code_postale): self
    {
        $this->code_postale = $code_postale;

        return $this;
    }
// ---------------------------------------------------------------------------------------------------

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }
// ---------------------------------------------------------------------------------------------------

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(string $pays): self
    {
        $this->pays = $pays;

        return $this;
    }
// ---------------------------------------------------------------------------------------------------

    /**
     * @return Collection|Chambre[]
     */
    public function getChambres(): Collection
    {
        return $this->chambres;
    }

    public function addChambre(Chambre $chambre): self
    {
        if (!$this->chambres->contains($chambre)) {
            $this->chambres[] = $chambre;
            $chambre->setHopital($this);
        }

        return $this;
    }

    public function removeChambre(Chambre $chambre): self
    {
        if ($this->chambres->contains($chambre)) {
            $this->chambres->removeElement($chambre);
            // set the owning side to null (unless already changed)
            if ($chambre->getHopital() === $this) {
                $chambre->setHopital(null);
            }
        }

        return $this;
    }
// ---------------------------------------------------------------------------------------------------

}

src/Form/HopitalType.php
<?php

namespace App\Form;

use App\Entity\Hopital;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class HopitalType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('adresse')
            ->add('code_postale')
            ->add('ville')
            ->add('pays')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Hopital::class,
        ]);
    }
}

src/Controller/HopitalController.php
<?php

namespace App\Controller;

use App\Entity\Chambre;
use App\Entity\Hopital;
use App\Form\HopitalType;
use App\Form\ChambreType;
use App\Repository\HopitalRepository;
use App\Repository\AdmissionRepository;
use App\Repository\ChambreRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/hopital")
 */
class HopitalController extends AbstractController
{
    /**
     * @Route("/", name="hopital_index", methods={"GET"})
     */
    public function index(HopitalRepository $hopitalRepository): Response
    {
        return $this->render('hopital/index.html.twig', [
            'hopitals' => $hopitalRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="hopital_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $hopital = new Hopital();
        $form = $this->createForm(HopitalType::class, $hopital);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($hopital);
            $entityManager->flush();

            return $this->redirectToRoute('hopital_index');
        }

        return $this->render('hopital/new.html.twig', [
            'hopital' => $hopital,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="hopital_show", methods={"GET"})
     */
    public function show(Hopital $hopital, /*Patient $patient,*/ ChambreRepository $chambreRepository): Response
    {
        // $repo = $this-> getDoctrine()->getRepository(Hopital :: class);      
        return $this->render('hopital/show.html.twig', [
            'hopital' => $hopital,
            'chambres'=> $chambreRepository->findAll($hopital),
            // 'patient' => $patient,
            ]);
        }
        
        /**
         * @Route("/{id}/edit", name="hopital_edit", methods={"GET","POST"})
         */
        public function edit(Request $request, Hopital $hopital): Response
        {
            $form = $this->createForm(HopitalType::class, $hopital);
            $form->handleRequest($request);
            
            if ($form->isSubmitted() && $form->isValid()) {
                $this->getDoctrine()->getManager()->flush();
                
                return $this->redirectToRoute('hopital_index');
            }
            
            return $this->render('hopital/edit.html.twig', [
                'hopital' => $hopital,
                'form' => $form->createView(),

        ]);
    }

    /**
     * @Route("/{id}", name="hopital_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Hopital $hopital): Response
    {
        if ($this->isCsrfTokenValid('delete'.$hopital->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($hopital);
            $entityManager->flush();
        }

        return $this->redirectToRoute('hopital_index');
    }
}

templates/hopital/_delete_form.html.twig
<form method="post" action="{{ path('hopital_delete', {'id': hopital.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ hopital.id) }}">
    <button class="btn">Delete</button>
</form>

templates/hopital/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/hopital/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Hopital{% endblock %}

{% block body %}
    <h1>Edit Hopital</h1>

    {{ include('hopital/_form.html.twig', {'button_label': 'Update'}) }}

<h2>Liste des chambres</h2>
    <p>petit probleme d'agenda pour les admissions sorry ¯\_(ツ)_/¯</p>

{% for chambre in hopital.chambres %}
<ul>
    <li>
    {{ chambre.nom }} 

    {{ include('chambre/_delete_form.html.twig') }}</a>
    </li>
</ul>
{% endfor %}

    <a href="{{ path('hopital_index') }}">retour à la liste</a>

    {{ include('hopital/_delete_form.html.twig') }}
{% endblock %}

templates/hopital/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hopital index{% endblock %}

{% block body %}
    <h1>Hopital index</h1>
    <p>edit uniquement depuis ici sorry ¯\_(ツ)_/¯</p>

    <table class="table">
        <thead>
            <tr>
                {# <th>Id</th> #}
                <th>Nom</th>
                {# <th>Adresse</th>
                <th>Code_postale</th>
                <th>Ville</th>
                <th>Pays</th>
                <th>actions</th> #}
            </tr>
        </thead>
        <tbody>
        {% for hopital in hopitals %}
            <tr>
                {# <td>{{ hopital.id }}</td> #}
                <td>{{ hopital.nom }}</td>
                {# <td>{{ hopital.adresse }}</td>
                <td>{{ hopital.codePostale }}</td>
                <td>{{ hopital.ville }}</td>
                <td>{{ hopital.pays }}</td> #}
                <td>
                    <a href="{{ path('hopital_show', {'id': hopital.id}) }}">show</a>
                    <br>
                    <a href="{{ path('hopital_edit', {'id': hopital.id}) }}">edit</a>
                    {# <a href="{{ path('hopital_delete', {'id': hopital.id}) }}">delete</a> #}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {# <a href="{{ path('hopital_new') }}">Create new</a> #}
{% endblock %}

templates/hopital/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hopital{% endblock %}

{% block body %}

<h1>Hopital</h1>

<table class="table">
    <tbody>
        {# <tr>
            <th>Id</th>
            <td>{{ hopital.id }}</td>
        </tr> #}
        <tr>
            <th>Nom</th>
            <td>{{ hopital.nom }}</td>
        </tr>
        {# <tr>
            <th>Adresse</th>
            <td>{{ hopital.adresse }}</td>
        </tr>
        <tr>
            <th>Code_postale</th>
            <td>{{ hopital.codePostale }}</td>
        </tr>
        <tr>
            <th>Ville</th>
            <td>{{ hopital.ville }}</td>
        </tr>
        <tr>
            <th>Pays</th>
            <td>{{ hopital.pays }}</td>
        </tr> #}
    </tbody>
</table>
<a href="{{ path('hopital_edit', {'id': hopital.id}) }}">edit</a>
<h2>Liste des chambres</h2>
{% for chambre in hopital.chambres %}
<ul>
    <li>{{ chambre.nom }}</li> 
    <a href="{{ path('patient_show', {'id': admission.patient.id}) }}">show</a>

    {% for admission in chambre.admissions %}
        Date d'entrée : {{ admission.dateDebut|date('d.m.Y')}}
        <ul>
            <li>Patient : {{ admission.patient }}</li>
            <a href="{{ path('patient_show', ({'id': admission.patient.id})) }}"> Plus d'information </a>
        </ul>
    {% endfor %}
</ul>
{% endfor %}

<a href="{{ path('hopital_index') }}">back to list</a>

<a href="{{ path('hopital_edit', { id: hopital.id }) }}">edit</a>

{{ include("hopital/_delete_form.html.twig") }}
{% endblock %}