src/Entity/Admission.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AdmissionRepository")
 */
class Admission
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_debut;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_fin;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Patient", inversedBy="admissions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $patient;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Chambre", inversedBy="admissions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $chambre;
// ---------------------------------------------------------------------------------------------------

    public function getId(): ?int
    {
        return $this->id;
    }
// ---------------------------------------------------------------------------------------------------

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;
        
        return $this;
    }
// ---------------------------------------------------------------------------------------------------
    public function __construct()
    {
        $this->setDateDebut = (new \DateTime('now'));
    }

// ---------------------------------------------------------------------------------------------------

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;
        
        return $this;
    }
// ---------------------------------------------------------------------------------------------------

    public function getPatient(): ?patient
    {
        return $this->patient;
    }

    public function setPatient(?patient $patient): self
    {
        $this->patient = $patient;
        
        return $this;
    }
// ---------------------------------------------------------------------------------------------------

    public function getChambre(): ?chambre
    {
        return $this->chambre;
    }

    public function setChambre(?chambre $chambre): self
    {
        $this->chambre = $chambre;
        
        return $this;
    }
// ---------------------------------------------------------------------------------------------------

}

src/Form/AdmissionType.php
<?php

namespace App\Form;

use App\Entity\Admission;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AdmissionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            // ->add('date_debut')
            // ->add('date_fin')
            // ->add('patient')
            ->add('chambre')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Admission::class,
        ]);
    }
}

src/Controller/AdmissionController.php
<?php

namespace App\Controller;

use App\Entity\Admission;
use App\Form\AdmissionType;
use App\Repository\AdmissionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admission")
 */
class AdmissionController extends AbstractController
{
    /**
     * @Route("/", name="admission_index", methods={"GET"})
     */
    public function index(AdmissionRepository $admissionRepository): Response
    {
        return $this->render('admission/index.html.twig', [
            'admissions' => $admissionRepository->findAll(),
        ]);
    }

    // /**
    //  * @Route("/new", name="admission_new", methods={"GET","POST"})
    //  */
    // public function new(Request $request): Response
    // {
    //     $admission = new Admission();
    //     $form = $this->createForm(AdmissionType::class, $admission);
    //     $form->handleRequest($request);

    //     if ($form->isSubmitted() && $form->isValid()) {
    //         $entityManager = $this->getDoctrine()->getManager();
    //         $entityManager->persist($admission);
    //         $entityManager->flush();

    //         return $this->redirectToRoute('admission_index');
    //     }

    //     return $this->render('admission/new.html.twig', [
    //         'admission' => $admission,
    //         'form' => $form->createView(),
    //     ]);
    // }

    // /**
    //  * @Route("/{id}", name="admission_show", methods={"GET"})
    //  */
    // public function show(Admission $admission): Response
    // {
    //     return $this->render('admission/show.html.twig', [
    //         'admission' => $admission,
    //     ]);
    // }

    // /**
    //  * @Route("/{id}/edit", name="admission_edit", methods={"GET","POST"})
    //  */
    // public function edit(Request $request, Admission $admission): Response
    // {
    //     $form = $this->createForm(AdmissionType::class, $admission);
    //     $form->handleRequest($request);

    //     if ($form->isSubmitted() && $form->isValid()) {
    //         $this->getDoctrine()->getManager()->flush();

    //         return $this->redirectToRoute('admission_index');
    //     }

    //     return $this->render('admission/edit.html.twig', [
    //         'admission' => $admission,
    //         'form' => $form->createView(),
    //     ]);
    // }

    /**
     * @Route("/{id}", name="admission_cloturer", methods={"POST"})
     */
    public function cloturer(Request $request, Admission $admission): Response
    {
        if ($this->isCsrfTokenValid('cloturer'.$admission->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $admission->setDateFin(new \DateTime('now')); // MAINTENANT MAINTENANT MAINTENANT !!
            $entityManager->flush();
        }

        return $this->redirectToRoute('admission_index');
    }
}

templates/admission/_delete_form.html.twig
<form method="post" action="{{ path('admission_cloturer', {'id': admission.id}) }}" onsubmit="return confirm('Are you sure you want to cloturer this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('cloturer' ~ admission.id) }}">
    <button class="btn">cloturer</button>
</form>

templates/admission/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/admission/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Admission index{% endblock %}

{% block body %}
    <h1>Admission index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date_debut</th>
                <th>Date_fin</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for admission in admissions %}
            <tr>
                <td>{{ admission.id }}</td>
                <td>{{ admission.dateDebut ? admission.dateDebut|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ admission.dateFin ? admission.dateFin|date('Y-m-d H:i:s') : '' }}</td>
                
                {% if admission.dateFin == null %}
                <td>
                    {{ include('admission/_delete_form.html.twig') }}
                </td>
                {% endif %}
            </tr>
        {% else %}
            <tr>
                <td colspan="4">rien trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {# <a href="{{ path('admission_new') }}">Create new</a> #}
{% endblock %}